from textclusteringDBSCAN.textclustering.encoders import BertEncoder
from pandas import DataFrame

import numpy as np
encoder = BertEncoder()

class DistilBertVectorizer():
    """ Object to store the data prepared for clustering """
    def __init__(self,data: DataFrame, target_col: str):
        self.data = data
        self.target_col = target_col

    def vectorize(self):
        """ Adding the column 'transformer_vector' to the data. The column contains vector representations of the
        text from the target column. Representations are generated by DistilBert """

        vectors = encoder.bert_encode(self.data[self.target_col])
        self.data['transformer_vector'] = [np.array(list(vec)) for vec in vectors]
